development:
  adapter: postgresql
  encoding: unicode
  database: my_portfolio_development
  pool: 5
  username: my_portfolio
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_portfolio_test
  pool: 5
  username: my_portfolio
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_portfolio_production
  pool: 5
  username: my_portfolio
  password:
